#!/bin/bash

/usr/bin/google-chrome "$@"&

for i in 1 2 3
do
	sleep 1 
	pid_to_kill=`ps aux | grep 'S[+ ].*chrome$' | awk '{print $2}'`
	if [ ! -z "$pid_to_kill" ]; then
		echo "Duplicate process detected. Stopping the duplicate."
		echo $pid_to_kill
		kill $pid_to_kill
	fi
done
