#!/bin/bash

/usr/bin/google-chrome "$@"&

for i in 1 2 3 4 5
do
	sleep 1 
	echo $i
	pids_to_kill=`ps aux | grep 'S[+ ].*/opt/google/chrome/chrome$' | awk '{print $2}'`
	if [ ! -z "$pids_to_kill" ]; then
		echo "Duplicate processes detected. Stopping the duplicates."
		echo $pids_to_kill
		kill $pids_to_kill
	fi
done
